# Generated by Django 3.1.3 on 2021-09-23 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=64)),
                ('apellidos', models.CharField(max_length=64)),
                ('direccion', models.CharField(max_length=64, null=True)),
                ('telefonos', models.CharField(max_length=20, null=True)),
                ('email', models.CharField(max_length=64, null=True)),
                ('especialidad', models.CharField(max_length=64, null=True)),
                ('password', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=64)),
                ('apellidos', models.CharField(max_length=64)),
                ('direccion', models.CharField(max_length=64, null=True)),
                ('telefonos', models.CharField(max_length=20, null=True)),
                ('email', models.CharField(max_length=64, null=True)),
                ('password', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Disponibilidad',
            fields=[
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(null=True)),
                ('hora', models.TimeField(null=True)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appcitasmedicas.medico')),
            ],
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('cancelada', models.TextField(choices=[('S', 'Si'), ('N', 'No')], max_length=1)),
                ('hora_cancelada', models.TimeField(null=True)),
                ('disponibilidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appcitasmedicas.disponibilidad')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appcitasmedicas.paciente')),
            ],
        ),
    ]
