# Generated by Django 3.2.7 on 2021-10-06 12:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('appcitasmedicas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2021, 10, 6, 12, 47, 24, 400446, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='cita',
            name='hora_cancelada',
            field=models.TimeField(default=datetime.datetime(2021, 10, 6, 12, 47, 24, 400490, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='citahora',
            name='hora',
            field=models.TimeField(default=datetime.datetime(2021, 10, 6, 12, 47, 24, 400074, tzinfo=utc)),
        ),
    ]
