# Generated by Django 3.1.3 on 2021-09-23 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcitasmedicas', '0002_auto_20210923_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
