# Generated by Django 3.2.7 on 2021-10-06 17:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('appcitasmedicas', '0002_auto_20211006_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2021, 10, 6, 17, 40, 38, 770956, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='cita',
            name='hora_cancelada',
            field=models.TimeField(default=datetime.datetime(2021, 10, 6, 17, 40, 38, 770956, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='citahora',
            name='hora',
            field=models.TimeField(default=datetime.datetime(2021, 10, 6, 17, 40, 38, 770956, tzinfo=utc)),
        ),
    ]
