# Generated by Django 3.1.3 on 2021-09-23 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcitasmedicas', '0005_auto_20210923_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='cancelada',
            field=models.CharField(choices=[('S', 'Si'), ('N', 'No')], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='cita',
            name='hora_cancelada',
            field=models.TimeField(default='00:00'),
        ),
    ]
