# Generated by Django 3.1.3 on 2021-09-23 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcitasmedicas', '0006_auto_20210923_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='tipo_id',
            field=models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('CE', 'Cédula de Extranjería'), ('PA', 'Pasaporte'), ('PE', 'Permiso de Permanencia'), ('RC', 'Registro Civil'), ('TI', 'Tarjeta de Identidad')], max_length=2, null=True),
        ),
    ]
