# Generated by Django 3.1.3 on 2021-09-23 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcitasmedicas', '0007_auto_20210923_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='disponibilidad',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
