# Generated by Django 3.1.3 on 2021-09-23 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appcitasmedicas', '0008_auto_20210923_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='disponibilidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appcitasmedicas.disponibilidad'),
        ),
        migrations.AlterField(
            model_name='disponibilidad',
            name='medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appcitasmedicas.medico'),
        ),
    ]
